// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYqtx0Rg_ImC6ufJv6ZMBiGm0RdBiO950',
    appId: '1:422631118526:web:c4ed278ddf5fe96340b0ef',
    messagingSenderId: '422631118526',
    projectId: 'daklakagent',
    authDomain: 'daklakagent.firebaseapp.com',
    storageBucket: 'daklakagent.firebasestorage.app',
    measurementId: 'G-Q2ZWSPL7Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp4Ooqe-eB_HoIuH056kKdMw0rlkvvhr8',
    appId: '1:422631118526:android:5a34a43374c0ceee40b0ef',
    messagingSenderId: '422631118526',
    projectId: 'daklakagent',
    storageBucket: 'daklakagent.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDxV9ownfk2hRIcLJKk7aCaZ42vkB0KOw',
    appId: '1:422631118526:ios:6236e01cb74c57a040b0ef',
    messagingSenderId: '422631118526',
    projectId: 'daklakagent',
    storageBucket: 'daklakagent.firebasestorage.app',
    iosBundleId: 'com.example.daklakagent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDxV9ownfk2hRIcLJKk7aCaZ42vkB0KOw',
    appId: '1:422631118526:ios:6236e01cb74c57a040b0ef',
    messagingSenderId: '422631118526',
    projectId: 'daklakagent',
    storageBucket: 'daklakagent.firebasestorage.app',
    iosBundleId: 'com.example.daklakagent',
  );
}
